---
title: "The Yard Community"
baseURL: "https://theyard.wherewemeet.app/"
theme: "zen"
languageCode: "en-GB"
defaultContentLanguage: "en"
pluralizelisttitles: false
removePathAccents: true
paginate: 100
paginatePath: "page"
rssLimit: 200
buildFuture: true
author:
  name: "Joe Jarlett"
  url: "https://joejarlett.co.uk"
  avatar: "path/to/some-image.jpg"

outputFormats:
  SearchIndex:
    mediaType: "application/json"
    baseName: "searchindex"
    isPlainText: true
    notAlternative: true

outputs:
  home: ["HTML", "RSS", "JSON", "SearchIndex"]
  section: ["HTML", "RSS", "JSON"]

params:
  contact: "joe.jarlett@gmail.com"
  #copyright: "Copyright 2021"
  description: "The Yard Community, St Werbughs, Bristol"
  dateformat: "Mon, 2 Jan 2006"
  favicon: "apple-touch-icon.png"
  feedlinks: false
  footer: ""
  icon: "apple-touch-icon.png"
  image: "apple-touch-icon.png"
  imageMaxWidth: 400
  mobileMenu: true
  poweredby: false
  sidebar: false
  submitted: false
  #jquery: true
  google_fonts: [
    ["Raleway", "400, 700"],
    ["Open Sans", "400, 400i, 700, 700i"]
  ]
  githubEdit: https://github.com/joejarlett/theyard/blob/develop/content/
