extends: eslint:recommended
env:
  browser: true
globals:
  jQuery: true
  u: true
rules:
  array-bracket-spacing:
    - "error"
    - never
  block-scoped-var: "error"
  brace-style:
    - "error"
    - stroustrup
    - allowSingleLine: true
  comma-dangle:
    - "error"
    - never
  comma-spacing: "error"
  comma-style:
    - "error"
    - last
  computed-property-spacing:
    - "error"
    - never
  curly:
    - "error"
    - all
  eol-last: "error"
  eqeqeq:
    - "error"
    - smart
  guard-for-in: "error"
  indent:
    - "error"
    - 2
    - SwitchCase: 1
  key-spacing:
    - "error"
    - afterColon: true
      beforeColon: false
  keyword-spacing:
    - "error"
    - after: true
      before: true
  linebreak-style:
    - "error"
    - unix
  lines-around-comment:
    - "error"
    - afterBlockComment: false
      beforeBlockComment: true
  max-nested-callbacks:
    - "warn"
    - 3
  new-parens: "error"
  no-array-constructor: "error"
  no-caller: "error"
  no-catch-shadow: "error"
  no-eval: "error"
  no-extend-native: "error"
  no-extra-bind: "error"
  no-extra-parens:
    - "error"
    - functions
  no-implied-eval: "error"
  no-iterator: "error"
  no-label-var: "error"
  no-labels: "error"
  no-lone-blocks: "error"
  no-loop-func: "error"
  no-multi-spaces: "error"
  no-multi-str: "error"
  no-native-reassign: "error"
  no-nested-ternary: "error"
  no-new-func: "error"
  no-new-object: "error"
  no-new-wrappers: "error"
  no-octal-escape: "error"
  no-process-exit: "error"
  no-proto: "error"
  no-return-assign: "error"
  no-script-url: "error"
  no-sequences: "error"
  no-shadow-restricted-names: "error"
  no-spaced-func: "error"
  no-trailing-spaces: "error"
  no-undef-init: "error"
  no-undefined: "error"
  no-unused-expressions: "error"
  no-unused-vars:
    - "error"
    - args: none
      vars: all
  no-with: "error"
  object-curly-spacing:
    - "error"
    - never
  one-var:
    - "error"
    - never
  quote-props:
    - "error"
    - consistent-as-needed
  quotes:
    - "error"
    - single
    - avoid-escape
  semi:
    - "error"
    - always
  semi-spacing:
    - "error"
    - after: true
      before: false
  space-before-blocks:
    - "error"
    - always
  space-before-function-paren:
    - "error"
    - anonymous: always
      named: never
  space-in-parens:
    - "error"
    - never
  space-infix-ops: "error"
  space-unary-ops:
    - "error"
    - nonwords: false
      words: true
  spaced-comment:
    - "error"
    - always
  strict: "error"
  valid-jsdoc:
    - "warn"
    - prefer:
        property: prop
        returns: return
      requireReturn: false
  yoda:
    - "error"
    - never
