name = "Zen"
description = "A solid base for your custom Hugo theme with pipes support for Sass and Javascript."
homepage = "https://github.com/frjo/hugo-theme-zen"
license = "GPLv2"
licenselink = "http://www.gnu.org/licenses/old-licenses/gpl-2.0.html"
tags = ["accessible", "multilingual", "responsive", "blog", "search", "micro", "podcast"]
features = ["accessible", "multilingual", "responsive", "grid", "sass", "search", "matamo", "jsonfeed", "subtheme", "podcast"]
min_version = "0.67.1"

[author]
  name = "Fredrik Jonsson"
  homepage = "https://xdeb.net/"

[original]
  name = "Drupal zen base theme"
  homepage = "https://www.drupal.org/project/zen"
  repo = "https://cgit.drupalcode.org/zen"
